
[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[general]
import = ["/home/mble/.config/alacritty/oxocarbon/oxocarbon-dark.toml"]

[terminal]

[terminal.shell]
program = "/home/mble/.config/alacritty/tmuxpath.sh"
